# frozen_string_literal: true
source 'http://rubygems.org'

ruby '2.3.0'

gem 'acl9', git: 'https://github.com/be9/acl9.git', branch: 'finalist-update-rails'
gem 'actionpack-action_caching', '~> 1.2'
gem 'active_interaction', '~> 3.5'
gem 'acts-as-taggable-on', '~> 4.0'
gem 'acts_as_api', '~> 0.4'
gem 'bootstrap-sass', '~> 3.3'
gem 'breadcrumbs', '~> 0.1'
gem 'devise', '~> 4.2'
gem 'exception_notification', '~> 2.6'
gem 'feed-abstract', '0.0.15'
gem 'font-awesome-rails', '~> 4.7'
gem 'formtastic', '~> 3.1'
gem 'formtastic-bootstrap', git: 'https://github.com/mjbellantoni/formtastic-bootstrap.git'
gem 'friendly_id', '~> 5.2'
gem 'haml-rails', '~> 0.9'
gem 'jquery-rails', '~> 4.2'
gem 'nokogiri', '~> 1.7'
gem 'pg', '~> 0.19'
gem 'progress_bar', '~> 1.1'
gem 'protected_attributes_continued', '~> 1.2' # TODO: switch to strong parameters
gem 'pundit', '~> 1.1'
gem 'rails', '~> 5.0'
gem 'rails-observers', git: 'https://github.com/rails/rails-observers.git'
gem 'sanitize', '~> 4.4'
gem 'sass-rails', '~> 5.0'
gem 'sidekiq', '~> 3.5'
gem 'sinatra', '~> 2.0.0.beta2', require: false
gem 'sprockets', '~> 3.7'
gem 'sunspot_rails', '~> 2.2'
gem 'sunspot_solr', '~> 2.2'
gem 'test-unit', '~> 3.2'
gem 'uglifier', '~> 2.7'
gem 'unicorn', '~> 4.9'
gem 'whenever', '~> 0.9'
gem 'will_paginate', '~> 3.1'
gem 'will_paginate-bootstrap', '~> 1.0'
gem 'non-stupid-digest-assets', '~> 1.0', '>= 1.0.9'

group :development do
  gem 'brakeman', '~> 3.6'
  gem 'drg', '~> 1.5'
  gem 'haml_lint', '~> 0.21'
  gem 'rubocop', '~> 0.47'
  gem 'rubocop-rspec', '~> 1.10'
  gem 'spring', '~> 2.0'
  gem 'spring-commands-rspec', '~> 1.0'
  gem 'spring-commands-rubocop', '~> 0.2'
  gem 'web-console', '~> 3.4'
end

group :development, :test do
  gem 'awesome_print', '~> 1.7'
  gem 'pry', '~> 0.10'
  gem 'pry-byebug', '~> 3.4'
  gem 'pry-rails', '~> 0.3'
  gem 'rspec-rails', '~> 3.5'
  gem 'sqlite3', '~> 1.3'
  gem 'therubyracer', '~> 0.12'
end

group :test do
  gem 'capybara-webkit', '~> 1.12'
  gem 'database_cleaner', '~> 1.5'
  gem 'factory_girl_rails', '~> 4.8'
  gem 'fuubar', '~> 2.2'
  gem 'headless', '~> 2.3'
  gem 'launchy', '~> 2.4'
  gem 'pundit-matchers', '~> 1.1'
  gem 'selenium-client', '~> 1.2'
  gem 'selenium-webdriver', '~> 3.0'
  gem 'shoulda-matchers', '~> 3.1'
  gem 'vcr', '~> 3.0'
  gem 'webmock', '~> 2.3'
end
